baseurl: "https://hugo-shoelaces.netlify.app"
# override .Site.Title for copyright notice
# copyright: "Custom Business Name"
canonifyURLs: false
disableAliases: true
disableHugoGeneratorInject: true
disableKinds: ["taxonomy", "taxonomyTerm"]
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
# googleAnalytics: 
languageCode: "en-US"
paginate: 7
rssLimit: 10
title: "Shoelaces Template"

# add redirects/headers
outputs:
  home: ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
mediaTypes:
  text/netlify:
    suffixes: [""]
    delimiter: ""


outputFormats:
  # add output format for netlify _redirects  
  REDIRECTS:
    mediatype: "text/netlify"
    baseName: "_redirects"
    isPlainText: true
    notAlternative: true
  # add output format for netlify _headers
  HEADERS:
    mediatype: "text/netlify"
    baseName: "_headers"
    isPlainText: true
    notAlternative: true

caches:
    getjson:
      dir: ":cacheDir/:project"
      maxAge: "10s"

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5

taxonomies:
  category: "categories"

permalinks:
  blog: "/:title/"

minify:
  tdewolff:
    html:
      keepWhitespace: false

related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
  - name: "categories"
    weight: 100
  - name: "date"
    weight: 10

module:
  imports:
  - path: github.com/future-wd/hugo-image
  - path: github.com/future-wd/hugo-svg-font/v2
