# Meta Data for SEO

## Page Title
titleSeparator: "-"
# only used on home page
titleAddition: "Modern Hugo Starter"
# fall back description if a page does not have a description. Good to use for home page
description: "Hyas is a Hugo starter helping you build modern websites that are secure, fast, and SEO-ready — by default."

## Open Graph
images: ["hyas.png"]
ogLocale: "en_US"
titleHome: "Hyas Hugo Starter"

## Twitter Cards
twitterSite: "@gethyas"
twitterCreator: "@henkverlinde"

## JSON-LD
# schemaType: "Person"
# schemaType: "Organization"
# schemaName: "Hyas"
# schemaAuthor: "Henk Verlinde"
# schemaAuthorTwitter: "https://twitter.com/henkverlinde"
# schemaAuthorLinkedIn: "https://www.linkedin.com/in/henkverlinde/"
# schemaAuthorGitHub: "https://github.com/h-enk"
# schemaLocale: "en-US"
# schemaLogo: "logo-hyas.png"
# schemaLogoWidth: 512
# schemaLogoHeight: 512
# schemaImage: "hyas.png"
# schemaImageWidth: 1280
# schemaImageHeight: 640
# schemaTwitter: "https://twitter.com/gethyas"
# schemaLinkedIn: ""
# schemaGitHub: "https://github.com/h-enk/hyas"

## Chrome Browser
themeColor: "#fff"

# Images
quality: 85
bgColor: "#fff"
landscapePhotoWidths: [900, 800, 700, 600, 500]
portraitPhotoWidths: [800, 700, 600, 500]
lqipWidth: "20x"
smallLimit: "300"

# Footer - override default copyright message
# footer: "Custom Footer Text"

# Alert
alert: false
alertText: "Deliver web projects 10x faster. <a class=\"alert-link\" href=\"https://www.netlify.com/whitepaper/\" target=\"_blank\" rel=\"noopener\">Get the free enterprise paper →</a>"

social:
  twitter:
    # account is for twitter cards, include @
    account: "@handle"
    url: http://www.twitter.com/user
    icon: icons/bootstrap/twitter
  facebook:
    url: http://www.facebook.com/user
    icon: icons/bootstrap/facebook
    # Facebook Page Admin ID for Domain Insights
    facebook_admin: 
  github:
    url: "http://www.github.com/user"
    icon: "icons/bootstrap/github"
    disable: false
# https://schema.org/Organization
## JSON-LD
schemaType: "Organization"
  # schemaType: "Person"
contact:
  # https://schema.org/PostalAddress
  address:
  # first record is for schema
  - name: Address
    streetAddress: 
    - 48 Pirrama Rd
    addressLocality: Pyrmont
    addressRegion: NSW
    postalCode: 2009
    addressCountry: Australia
    # hasMap
    url: https://goo.gl/maps/2bHxJ3bfhtHtnx2b9
    geo: #coordinates 
    icon: icons/bootstrap/geo-alt
    disable: false
  # postal address is just for contact details display
  # servicePostalAddress:
  #   postOfficeBoxNumber:
  #   addressLocality: Pyrmont
  #   addressRegion: NSW
  #   postalCode: 2009
  #   addressCountry: Australia

  openingHours:
  - name: Opening Hours
    icon: icons/bootstrap/clock
    hours:
    - dayOfWeek: Monday
      opens: 
        data: "09:00:00"
        text: 9:00 AM
      closes: 
        data: "17:00:00"
        text: 5:00 PM
    - dayOfWeek: Tuesday
      opens: 
        data: "09:00:00"
        text: 9:00 AM
      closes: 
        data: "17:00:00"
        text: 5:00 PM
    - dayOfWeek: Saturday
      custom: By Appointment
    - dayOfWeek: Sunday
      custom: Closed
  telephone:
  # first record appears in schema data
  - name: Phone
    text: (02) 8004 3293
    url: "tel:+61280043293"
    icon: icons/bootstrap/phone
    disable: false
  # mobile
  # - text:
  #   url:
  #   icon: icons/bootstrap/telephone
  #   disable: false
  email: 
  - name: Email
    text: test@domain.com
    url: "mailto:test@domain.com"
    icon: icons/bootstrap/envelope
    disable: false
# only for contact details display
  extraItem:
  - name: Help Desk
    text: Help Desk
    url: helpdesk.com
    icon: 
    disable: true


# founder:
# foundingDate:
# foundingLocation:
# logo


image:
  formats: ["original", "webp"]
  loading: lazy
  layout: responsive
  objectFit: cover
  minWidth: 500
  maxWidth: 4000
  deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840]
  imageSizes: [16, 32, 48, 64, 96, 128, 256, 384]
  #css: 
  placeholder:
    style: blur # empty | color | blur | solid (blur/solid js or inline type only)
    type: js  # css | js | inline
    blur:
      amount: 3
      size: 50
    # nativePlaceholder: none or colour value
    # libraryPlaceholder: blur, none, colour
  link:
    class:
    rel: 
    target: 
    #css: 
  figure:
    class: figure # .figureCSS to target figures
    titleClass: h4
    imageClass: figure-img
    figcaptionClass: figure-caption
    attrLinkClass: ""
    #css: 
  lazyLibrary:
    enable: true
    dataSrcset: true
    dataSrc: true
    dataSizes: true
    class: lazyload # can be array/slice
    #  imageCSS: "display:block;width:100%;" # add to css, but configure here?
    #  figureCSS: "display:block!important;" # add to css, but configure here? img.image and figure.[figure.class] (takes )
    # add to css 
    # $lazyLibraryFigureStyle := site.Params.image.lazyLibrary.figureStyle
    noscript: true